name: Basic Workflow
on: [push]

jobs:
  setup-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Git User with Custom Remote
        uses: jamie-codez/setup-git-user@v1
        with:
          username: 'John Doe'
          email: 'john.doe@example.com'
          remote-url: 'https://git.com/myorg/myrepo.git'
          token: ${{secrets.GITHUB_TOKEN}}